import { CrudHistory } from "./crud-history-item";

export interface RateItem {
    Id: number,
    Term: number,
    IdProduct: number,
    IdClassType: number,
    ClassCode: null | string,
    MaxKm: number,
    Deductible: number,
    PriceCert: number,
    PriceEW: number,
    PriceWP: number,
    MKT: number,
    PlanCodeEW: number,
    PriceRA: number,
    PlanCodeRA: number,
    Prime: number,
    AgencyComission: number,
    VendorComission: number,
    DealerComission: number,
    AdminFee: number,
    InsurancePolicy: number,
    CommAnzen: number,
    Rewards: number,
    CommNR: number,
    CommPlant: number,
    RiskPremium: number,
    Profit: number,
    IdProgram: number,
    Taxes_Percent: number,
    CrudHistoryList: string,
    ManufacturerTerm: number,
    ManufacturerWarrantyKM: number,
    Recuperacion: number,
    APV: number,
    Adicional1: number,
    Adicional2: number,
    PrimaNeta: number
    Active: boolean
}